#YAML es un formato de serialización de datos legible por humanos 

scara_robot_left:
  #Publicar todos los estados de los angulos del brazo------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    #tiempo de contancia en publicar
    publish_rate: 50

  #Controlador de la pocision del robot---------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    #angulo del robot
    joint: rotation1
    #Control para cambios bruscos: Controlado proporciona-integral-derivativo
    #Controlador PID
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: rotation2
    pid: {p: 100.0, i: 0.01, d: 10.0}